### ISSUE TITLE
Crash in multiplayer when pressing H

### ISSUE THREAD

**Issue by Ghost-chu** [mineTomek/Panoramas#1]
```
[01:46:51] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.integrated.IntegratedServer.getSavePath(net.minecraft.util.WorldSavePath)" because the return value of "net.minecraft.client.MinecraftClient.getServer()" is null
	at com.panoramas.PanoramasClient.lambda$onInitializeClient$0(PanoramasClient.java:36) ~[panoramas-0.0.2.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.2.3+78d798af4f-23d986bd14341f63.jar:?]
	at net.minecraft.client.MinecraftClient.handler$bnd000$fabric-lifecycle-events-v1$onEndTick(MinecraftClient.java:15277) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:2067) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
[01:46:51] [Render thread/INFO]: Stopping worker threads
[01:46:52] [Render thread/INFO]: emissive suffixes loaded: {_e}.
[01:46:52] [Render thread/INFO]: Clearing 'BetterStatsClientNetworkHandler' flags.
[01:46:52] [Render thread/INFO]: [FastQuit] Exiting FastQuit.
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-01-25 01:46:52
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.minecraft.server.integrated.IntegratedServer.getSavePath(net.minecraft.util.WorldSavePath)" because the return value of "net.minecraft.client.MinecraftClient.getServer()" is null
	at com.panoramas.PanoramasClient.lambda$onInitializeClient$0(PanoramasClient.java:36)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at MC//net.minecraft.client.MinecraftClient.handler$bnd000$fabric-lifecycle-events-v1$onEndTick(MinecraftClient.java:15277)
	at MC//net.minecraft.client.MinecraftClient.tick(MinecraftClient.java:2067)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1289)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.panoramas.PanoramasClient.lambda$onInitializeClient$0(PanoramasClient.java:36)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at MC//net.minecraft.client.MinecraftClient.handler$bnd000$fabric-lifecycle-events-v1$onEndTick(MinecraftClient.java:15277)
Mixins in Stacktrace: None found

-- Uptime --
Details:
	JVM uptime: 392.567s
	Wall uptime: 369.557s
	High-res time: 358.227s
	Client ticks: 6574 ticks / 328.700s
Stacktrace:
	at MC//net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2564)
	at MC//net.minecraft.client.MinecraftClient.printCrashReport(MinecraftClient.java:995)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:911)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Mixins in Stacktrace:
	net.minecraft.client.main.Main:
		link.infra.screenshotclipboard.common.mixin.AWTHackMixin (screenshotclipboard-common.mixins.json)

-- Affected level --
Details:
	All players: 1 total; [class_746['Ghost_chu'/626754, l='ClientLevel', x=8547.85, y=122.98, z=-1328.76]]
	Chunk stats: 1024, 145 F: 3165 L: 0 U: 3068
	Level dimension: minecraft:overworld
	Level spawn location: World: (-644,35,-1562), Section: (at 12,3,6 in -41,2,-98; chunk contains blocks -656,-64,-1568 to -641,319,-1553), Region: (-2,-4; contains chunks -64,-128 to -33,-97, blocks -1024,-64,-2048 to -513,319,-1537)
	Level time: 3371261987 game time, 1033848011 day time
	Server brand: Purpur (Velocity)
	Server type: Non-integrated multiplayer server
	Tracked entity count: 161

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, continuity:glass_pane_culling_fix, continuity:default, file/SodiumTranslations.zip, file/Mod Menu Helper.zip, file/Chat Reporting Helper.zip, file/Fast Better Grass.zip, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 706001032 bytes (673 MiB) / 2468347904 bytes (2354 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3070 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x24dd
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4665
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 53100.06
	Virtual memory used (MB): 35923.91
	Swap memory total (MB): 20480.00
	Swap memory used (MB): 331.88
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		advancementplaques: Advancement Plaques 1.5.1
		advancementscreenshot: Advancement Screenshot 4.7
		animatica: Animatica 0.6+1.20
		architectury: Architectury 11.0.11
		async-pack-scan: Async Pack Scan 0.2.2
		authme: Auth Me 8.0.0+1.20.4
		badoptimizations: BadOptimizations 1.6.3
		balm-fabric: Balm 9.0.5
		bettercommandblockui: BetterCommandBlockUI 0.4.2
		bettermounthud: Better Mount HUD 1.2.2
		betterstats: Better Statistics Screen 3.7.1+fabric-1.20.4
			tcdcommons: TCD Commons API 3.7+fabric-1.20.4
		betterthirdperson: Better Third Person 1.9.0
		blockmeter: Block Meter 1.12.0
		boathud: BoatHud 1.1.5
		bobby: Bobby 5.0.3
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bookshelf: Bookshelf 23.0.2
		capes: Capes 1.5.3+1.20.2
		centered-crosshair: Centered Crosshair 1.0.6
		chatanimation: ChatAnimation 1.0.5
		cherishedworlds: Cherished Worlds 8.0.0+1.20.4
		clean-debug: Clean F3 0.4.4
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.30
		continuity: Continuity 3.0.0-beta.4+1.20.2
		controlify: Controlify 1.8.1+1.20.4
			dev_isxander_libsdl4j: libsdl4j 2.28.2-11
			org_hid4java_hid4java: hid4java 0.7.0
			org_quiltmc_quilt-json5: quilt-json5 1.0.3
		controlling: Controlling 15.0.2
		craftingtweaks: Crafting Tweaks 20.0.2
		customclientdns: CustomClientDNS 1.0-SNAPSHOT
			commons-validator_commons-validator: commons-validator 1.7
			dnsjava_dnsjava: dnsjava 3.5.2
			org_bspfsystems_yamlconfiguration: yamlconfiguration 1.4.0
		deathlog: DeathLog 0.3.2+1.20.3
		debugify: Debugify 1.20.4+1.0
		defaultoptions: Default Options 20.0.1
		durabilityviewer: Giselbaers Durability Viewer 1.20.4-fabric0.91.2-1.10.5
			cardinal-components-base: Cardinal Components API (base) 5.3.0
			cardinal-components-entity: Cardinal Components API (entities) 5.3.0
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.4+1.20
		dynamic-fullbright: Dynamic Fullbright 1.2.0
		dynamic_fps: Dynamic FPS 3.3.3
		effecttooltips: EffectTooltips 12.0.1
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.4+1.20.3
		enhancedblockentities: Enhanced Block Entities 0.9.1+1.20.2
			advanced_runtime_resource_pack: Runtime Resource Pack 0.8.0
			spruceui: SpruceUI 5.0.3+1.20.2
		entity_model_features: Entity Model Features 1.2.3
		entity_texture_features: Entity Texture Features 5.2.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.3.1
		equipmentcompare: Equipment Compare 1.3.8
		euphoria_patcher: Euphoria Patcher 0.3.0-fabric
			io_sigpipe_jbsdiff: jbsdiff 1.0
		fabric-api: Fabric API 0.95.1+1.20.4
			fabric-api-base: Fabric API Base 0.4.36+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.47+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.15+78d798af4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.46+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.7+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.10+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+25e1b4764f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.22+78d798af4f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+44c0f8c64f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.72+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.21+78d798af4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.41+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.39+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.30+78d798af4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.5+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.60+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.8+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.7+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.9+06274a474f
			fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.18+78d798af4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.4+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.4+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.52+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.33+78d798af4f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.55+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.1.0+0d29db764f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.16+78d798af4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.17+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.17+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.8+e84342304f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.6
			mixinextras: MixinExtras 0.3.2
		fabricskyboxes: FabricSkyBoxes 0.7.3+mc1.20.2
		fabrishot: Fabrishot 1.12.1
		fadeless: Fadeless 1.0.1
		fastipping: Fast IP Ping 1.0.1
		fastquit: FastQuit 3.0.0+1.20.4
		ferritecore: FerriteCore 6.0.3
		forgeconfigapiport: Forge Config API Port 20.4.3
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		fsb-interop: FabricSkyBoxes Interop 1.3.6+mc1.20.2-build.52
		gamemenuremovegfarb: Game Menu Remove GFARB 2.1.2
		iceberg: Iceberg 1.1.18
		immediatelyfast: ImmediatelyFast 1.2.8+1.20.4
			net_lenni0451_reflect: Reflect 1.3.1
		indium: Indium 1.0.28+mc1.20.4
		inventoryprofilesnext: Inventory Profiles Next 1.10.9
		invmove: InvMove 0.8.5
		iris: Iris 1.6.14
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		isxander-main-menu-credits: Main Menu Credits 1.1.2
		itemborders: Item Borders 1.2.1
		itemswapper: ItemSwapper 0.5.5
		jade: Jade 13.2.1
		java: OpenJDK 64-Bit Server VM 17
		languagereload: Language Reload 1.5.10+1.20.3
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 4.0.1
		libjf: LibJF 3.14.1
			libjf-base: LibJF Base 3.14.1
			libjf-config-commands: LibJF Config Commands 3.14.1
			libjf-config-core-v2: LibJF Config 3.14.1
			libjf-config-network-v0: LibJF Config: Network 3.14.1
			libjf-config-ui-tiny: LibJF Config UI: Tiny 3.14.1
			libjf-data-manipulation-v0: LibJF Data Manipulation 3.14.1
			libjf-data-v0: LibJF Data 3.14.1
			libjf-mainhttp-v0: LibJF MainHTTP 3.14.1
			libjf-translate-v1: LibJF Translate 3.14.1
			libjf-unsafe-v0: LibJF Unsafe 3.14.1
			libjf-web-v1: LibJF Web 3.14.1
		litematica: Litematica 0.17.0
		lithium: Lithium 0.12.1
		malilib: MaLiLib 0.18.0
		maptooltip: Map Tooltip 3.0.0
		mcwifipnp: LAN World Plug-n-Play 1.6.9
		memoryusagescreen: Memory Usage Screen 1.9.0
		midnightlib: MidnightLib 1.5.3
		minecraft: Minecraft 1.20.4
		mixintrace: MixinTrace 1.1.1+1.17
		mod-loading-screen: Mod Loading Screen 1.0.4
			com_formdev_flatlaf: flatlaf 3.0
		modelfix: Model Gap Fix 1.14
		modernfix: ModernFix 5.12.1+mc1.20.4
		modmenu: Mod Menu 9.0.0
		morechathistory: MoreChatHistory 1.1.1
		mousewheelie: Mouse Wheelie 1.13.3+mc1.20.4
			amecsapi: Amecs API 1.5.6+mc1.20.2
			coat: Coat 1.0.0-beta.22+mc1.20.4
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20.2
			tweed4_base: tweed4_base 1.7.1+mc1.20.2
			tweed4_data: tweed4_data 1.2.1+mc1.20.2
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20.2
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20.2
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20.2
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20.2
		narrus_yeetus: Narrus Yeetus 1.1.0
		nbtvoid: NBT Void 2.0.0
		no-telemetry: No Telemetry 1.8.0
		nochatclear: NoChatClear 1.0.0
		nochatreports: No Chat Reports 1.20.4-v2.5.0
		noisium: Noisium 1.0.2+mc1.20.x
		notenoughanimations: NotEnoughAnimations 1.7.0
		notes: Notes 1.20.4-2.1.0-fabric
		noxesium: Noxesium 1.2.0+669ccb7
			com_noxcrew_noxesium_api_: api 1.2.0+669ccb7
		nvidium: Nvidium 0.2.5-beta
		obsidianui: ObsidianUI 0.2.1+mc1.20.4
		optigui: OptiGUI 2.1.7
			optiglue: OptiGlue 2.1.7-mc.1.19.3
			org_apache_commons_commons-text: commons-text 1.10.0
			org_ini4j_ini4j: ini4j 0.5.4
		owo: oωo 0.12.3+1.20.3
		paginatedadvancements: Paginated Advancements 2.4.2
		panorama_screens: Panorama Screens 1.0+fabric+mc1.20.4
		panoramas: Panoramas 0.0.2
		ping-wheel: Ping Wheel 1.7.1
		prism: Prism 1.0.6
		puzzle: Puzzle 1.6.1+1.20.4
			puzzle-base: Puzzle Base 1.6.1+1.20.4
			puzzle-gui: Puzzle GUI 1.6.1+1.20.4
			puzzle-models: Puzzle Models 1.6.1+1.20.4
			puzzle-splashscreen: Puzzle Splash Screen 1.6.1+1.20.4
		raised: Raised 3.1.1
		recursiveresources: Recursive Resources 2.5.2+1.20.4
			cicada: CICADA 0.5.2+1.20.2-plus
			shared-resources-api: Shared Resources API 1.5.2
		reeses-sodium-options: Reese's Sodium Options 1.7.0+mc1.20.2-build.97
		reicollapsibleentries: REI Collapsible Entries QOL 2.0.1
		replayfps: Replay FPS 0.2.1
			mixinsquared: MixinSquared 0.1.1
		replaymod: Replay Mod 1.20.4-2.6.14
		resourcepackchecker: Server Resource Pack Checker 1.20.4-1.1.5
		roughlyenoughitems: Roughly Enough Items 14.0.688
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 2.2.0
		ryoamiclights: RyoamicLights 0.2.1+mc1.20.4
		screenshot_organisation: Screenshot Organisation 1.3
		screenshotclipboard: Screenshot to Clipboard 1.0.9
		searchables: Searchables 1.0.3
		shulkerboxtooltip: Shulker Box Tooltip 4.0.8+1.20.4
		skinlayers3d: 3d-Skin-Layers 1.6.2
		smoothscrollingrefurbished: Smooth Scrolling Refurbished 1.1.2
		sodium: Sodium 0.5.5
		sodium-extra: Sodium Extra 0.5.3+mc1.20.2-build.114
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.20.4-1.3.1
		spark: spark 1.10.58
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		stack-to-nearby-chests: Stack to Nearby Chests 0.5.4
			libgui: LibGui 9.2.1+1.20.2
				jankson: Jankson 6.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
		stackdeobfuscator: StackDeobfuscator 1.4.2+bf1fc22
			dev_booky_common_: common 1.4.2+bf1fc22
			net_fabricmc_mapping-io: mapping-io 0.3.0
		stendhal: Stendhal 1.4.1-1.20.2
		stutterfix: StutterFix mc1.20.3-0.2.0
		toolstats: ToolStats 19.0.1
		twd-sasf: ServerAddressSpaceFix 0.1.4
		voxelmap: Voxelmap 1.20.4-1.12.17
		whoami: Who am I? 1.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.3.2+1.20.4
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yosbr: YOSBR 0.1.2
		zoomify: Zoomify 2.13.0
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Loaded Shaderpack: ComplementaryReimagined_r5.1.1 + EuphoriaPatches_1.2
		Profile: HIGH (+0 options changed by user)
	Launched Version: 1.20.4
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 546.65, NVIDIA Corporation
	Window size: 2560x1494
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. <target> enum is invalid; expected GL_RENDERBUFFER_EXT.' x 2
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 20/20 chunks
	Resource Packs: vanilla, fabric, continuity:glass_pane_culling_fix (incompatible), continuity:default (incompatible), file/SodiumTranslations.zip, file/Mod Menu Helper.zip, file/Chat Reporting Helper.zip, file/Fast Better Grass.zip
	Current Language: zh_cn
	Locale: en_CN
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics 
#@!@# Game crashed! Crash report saved to: #@!@# E:\MultiMC\instances\Barbatos Packs(1)\.minecraft\crash-reports\crash-2024-01-25_01.46.52-client.txt
[01:46:52] [Thread-34/INFO]: Saving all world maps
```

**Comment by mineTomek** [comment]
Hi!

Thanks for pointing that out. In the future can you use tools like [Pastebin](https://pastebin.com) to attach logs? It makes it easier to read.

I will get to fixing that now. Expect a new version soon.

**Comment by mineTomek** [comment]
Can you link the server you got this on? Obviously, only if you want to.

**Comment by Ghost-chu** [comment]
im sorry, its a whitelist, private, community so I cant share the server address.

**Comment by mineTomek** [comment]
Don't worry. I'll use a local server.

**Comment by mineTomek** [comment]
You can test the mod by downloading it here: [panoramas-0.0.3-fix-1.jar.zip](https://github.com/mineTomek/Panoramas/files/14103831/panoramas-0.0.3-fix-1.jar.zip). If it works, then I'll merge it.
Sometimes the `apply panorama` button doesn't work, then you can just turn of hiding panorama resource packs in mod's config and enable the pack manually. I will be working on that issue next.

**Comment by mineTomek** [comment]
I don't want others experiencing the issue longer so I'm going to merge this and it will be available as an update on Modrinth. If you have any other problems, fill free to open another issue.
